// Nicholas Huaman 2018

// These are all of the accounts. Congratulations if you made it here!


// Declare all account names by their email.

var allAccounts = [
	"spbong999@gmail.com",
 	/*"nicholas.hua@kcpupils.org"/*,
	"nicolas.elm.gar@kcpupils.org",
	"kayla.de.bru@kcpupils.org",
	"maria.men.man@kcpupils.org",
	"pedrotomas.cob.agu@kcpupils.org",
	"victor.arr.mar@kcpupils.org",
	"inigo.agu.viy@kcpupils.org",
	"gonzalo.pon.liz@kcpupils.org",
	"david.san.gar@kcpupils.org",
	"nicolas.elm.gar@kcpupils.org",
	"patrickthomas.sch@kcpupils.org",
	"lucasgabriel.sal.bev@kcpupils.org",
	"antonio.sie.per@kcpupils.org",
	"jorgegabriel.jof.vic@kcpupils.org",
	"nathan.wal.san@kcpupils.org",
	"gonzalo.agu.lag@kcpupils.org",
	"ahmed.fte@kcpupils.org",
	"rodrigo.par.rob@kcpupils.org",
	"semsema.aou@kcpupils.org",
	"nicolas.arr.gra@kcpupils.org",
	"juanpablo.bis@kcpupils.org",
	"alonso.cas@kcpupils.org",
	"david.eze.zam@kcpupils.org",
	"diego.mor.man@kcpupils.org",
	"andrew.row@kcpupils.org",
	"beatriz.tay.rod@kcpupils.org",
	"constanza.par.hor@kcpupils.org",
	"daniel.mar.her@kcpupils.org",
	"pablo.sai.mon@kcpupils.org",
	"borja.alf.vic@kcpupils.org",
	"matan.kes@kcpupils.org",
	"marts.vec@kcpupils.org",
	"marcos.car.val@kcpupils.org",
	"victor.arr.mar@kcpupils.org",
	"mrpekka740@gmail.com",
	"rodrigo.alv.bor@kcpupils.org",
	"rodrigo.dez.per@kcpupils.org"*/
];

// If you name all the Pro accounts the only ones remaining will be the basic. Get it?

var proAccounts = [
	"spbong999@gmail.com",
	/*"nicholas.hua@kcpupils.org"/*,
	"antonio.sie.per@kcpupils.org",
	"rodrigo.dez.per@kcpupils.org",
	"kayla.de.bru@kcpupils.org",
	"lucasgabriel.sal.bev@kcpupils.org",
	"nathan.wal.san@kcpupils.org",
	"maria.men.man@kcpupils.org",
	"inigo.agu.viy@kcpupils.org",
	"nicolas.elm.gar@kcpupils.org",
	"semsema.aou@kcpupils.org",
	"rodrigo.alv.bor@kcpupils.org",
	"jorgegabriel.jof.vic@kcpupils.org",
	"daniel.mar.her@kcpupils.org",
	"constanza.par.hor@kcpupils.org",
	"beatriz.tay.rod@kcpupils.org",
	"gonzalo.agu.lag@kcpupils.org",
	"david.san.gar@kcpupils.org",
	"nicolas.elm.gar@kcpupils.org",
	"matan.kes@kcpupils.org",
	"ahmed.fte@kcpupils.org",
	"gonzalo.pon.liz@kcpupils.org",
	"pedrotomas.cob.agu@kcpupils.org",
	"juanpablo.bis@kcpupils.org",
	"nicolas.arr.gra@kcpupils.org",
	"victor.arr.mar@kcpupils.org",
	"rodrigo.par.rob@kcpupils.org",
	"pablo.sai.mon@kcpupils.org",
	"patrickthomas.sch@kcpupils.org",
	"mrpekka740@gmail.com",
	"andrew.row@kcpupils.org",
	"borja.alf.vic@kcpupils.org",
	"diego.mor.man@kcpupils.org",
	"alonso.cas@kcpupils.org",
	"david.eze.zam@kcpupils.org"*/
];
